tag_prefix = ""
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
    "cargo set-version --workspace {{version}}",
]
post_bump_hooks = [
    "git push",
    "git push origin {{version}} --no-verify",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "rdf-store-rs"
owner = "EKGF"
authors = [
    { username = "jgeluk", signature = "Jacobus Geluk" },
]

[bump_profiles]
