[build]
incremental = true
#target = "x86_64-apple-darwin"
#target = "wasm32-unknown-unknown"

[cargo-new]
vcs = "git"
email = "someone@ekgf.org"

# Add this section because IntelliJ rust plugin does not
# support the "sparse" protocol very well (as opposed to "git" protocol)
[registries.crates-io]
protocol = "git"

[net]
git-fetch-with-cli = true   # use the `git` executable for git operations

[patch.crates-io]
#rdftk_core      = { path = "../rust-rdftk/rdftk_core" }
#rdftk_io        = { path = "../rust-rdftk/rdftk_io" }
#rdftk_iri       = { path = "../rust-rdftk/rdftk_iri" }
#rdftk_names     = { path = "../rust-rdftk/rdftk_names" }
#rdftk_ontology  = { path = "../rust-rdftk/rdftk_ontology" }
#rdftk_query     = { path = "../rust-rdftk/rdftk_query" }
#rdftk_skos      = { path = "../rust-rdftk/rdftk_skos" }

[term]
color = "always"

